name: IstioSM
services:
  istio:
    type: IstioMesh
    namespace: istio-system
    version: #will be filled dynamically in workflow
    settings:
      profile: demo
    traits:
      automaticSidecarInjection:
        namespaces:
          - default
  grafana:
    type: GrafanaIstioAddon
    version: #will be filled dynamically in workflow
    namespace: istio-system
    dependsOn:
      - istio
      - prometheus

  prometheus:
    type: PrometheusIstioAddon
    version: #will be filled dynamically in workflow
    namespace: istio-system
    dependsOn:
      - istio